sonar.organization=thorsten-klein
sonar.projectKey=thorsten-klein_denver

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.9,3.13

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
